### PR TITLE
Fix build with Clang

### PR DESCRIPTION
**Pull request by shadchin**
Output with error:
```
In file included from $(SOURCE_ROOT)/python3/src/Modules/_blake2/blake2b_impl.c:30:
$(SOURCE_ROOT)/python3/src/Modules/_blake2/impl/blake2b.c(31,23): error: conflicting types for '_mm_set_epi64x'
static inline __m128i _mm_set_epi64x( const uint64_t u1, const uint64_t u0 )
                      ^
$(TOOL_ROOT)/clang/14.0.6/include/emmintrin.h(3613,1): note: previous definition is here
_mm_set_epi64x(long long __q1, long long __q0)
^
1 error generated.
```

### CODE REVIEW

**Comment by sneves** [comment]
What system configuration caused this failure?

**Comment by shadchin** [comment]
Compile with Clang 14.0.6 and `-m32`
